In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
stats = pd.DataFrame()

In [3]:
for offset in range(0,32):
    # URL page we will scraping (see image above)
    url = "https://www.basketball-reference.com/play-index/psl_finder.cgi?request=1&match=single&type=per_game&per_minute_base=36&per_poss_base=100&lg_id=NBA&is_playoffs=N&year_min=1997&year_max=2020&franch_id=&season_start=1&season_end=2&age_min=0&age_max=99&shoot_hand=&height_min=0&height_max=99&birth_country_is=Y&birth_country=&birth_state=&college_id=&draft_year=&is_active=&debut_yr_nba_start=&debut_yr_nba_end=&is_hof=&is_as=&as_comp=gt&as_val=0&award=&pos_is_g=Y&pos_is_gf=Y&pos_is_f=Y&pos_is_fg=Y&pos_is_fc=Y&pos_is_c=Y&pos_is_cf=Y&qual=&c1stat=&c1comp=&c1val=&c2stat=&c2comp=&c2val=&c3stat=&c3comp=&c3val=&c4stat=&c4comp=&c4val=&c5stat=&c5comp=&c6mult=&c6stat=&order_by=player&order_by_asc=&offset={}".format(str(offset*100))
    
    # this is the HTML from the given URL
    html = urlopen(url)
    soup = BeautifulSoup(html)
    # use findALL() to get the column headers
    soup.findAll('tr', limit=2)
    # use getText()to extract the text we need into a list
    headers = [th.getText() for th in soup.findAll('tr', limit=2)[1].findAll('th')]
    # exclude the first column as we will not need the ranking order from Basketball Reference for the analysis
    headers = headers[1:]
    # avoid the first header row
    rows = soup.findAll('tr')[1:]
    
    
    player_stats = [[td.getText() for td in rows[i].findAll('td')]
                for i in range(len(rows))]
    
    stats = pd.concat([stats, pd.DataFrame(player_stats, columns = headers)]).reset_index(drop=True)

In [4]:
stats = stats[1:]

In [5]:
stats.head(10)

,Season,Age,Tm,Lg,Player,G,GS,MP,FG,FGA,...,BLK,TOV,PF,PTS,FG%,2P%,3P%,eFG%,FT%,TS%
1,1996-97,29,POR,NBA,Aleksandar Đorđević,8,0,7.6,1.0,2.0,...,0.0,0.6,0.4,3.1,.500,.333,.714,.656,.800,.687
2,2016-17,19,LAL,NBA,Ivica Zubac,38,11,16.0,3.3,6.3,...,0.9,0.8,1.7,7.5,.529,.536,.000,.529,.653,.547
3,2017-18,20,LAL,NBA,Ivica Zubac,43,0,9.5,1.4,2.8,...,0.3,0.6,1.1,3.7,.500,.504,.000,.500,.765,.557
4,2017-18,21,CLE,NBA,Ante Žižić,32,2,6.7,1.5,2.1,...,0.4,0.3,0.9,3.7,.731,.731,,.731,.724,.746
5,2018-19,22,CLE,NBA,Ante Žižić,59,25,18.3,3.1,5.6,...,0.4,1.0,1.9,7.8,.553,.553,,.553,.705,.590
6,2016-17,22,CHI,NBA,Paul Zipser,44,18,19.2,2.0,5.0,...,0.4,0.9,1.8,5.5,.398,.451,.333,.473,.775,.503
7,2017-18,23,CHI,NBA,Paul Zipser,54,12,15.3,1.5,4.3,...,0.3,0.8,1.6,4.0,.346,.355,.336,.425,.760,.445
8,2016-17,20,ORL,NBA,Stephen Zimmerman,19,0,5.7,0.5,1.6,...,0.3,0.2,0.9,1.2,.323,.323,,.323,.600,.346
9,2005-06,24,NJN,NBA,Derrick Zimmerman,2,0,16.0,1.0,1.5,...,0.0,2.0,2.0,2.0,.667,.667,,.667,,.667
10,1996-97,23,TOT,NBA,George Zídek,52,2,7.2,0.9,2.3,...,0.1,0.5,1.2,2.8,.415,.422,.000,.415,.789,.500

In [6]:
stats.shape

(3359, 31)

In [7]:
stats_adv = pd.DataFrame()

In [8]:
for offset in range(0,32):
    # URL page we will scraping
    url = "https://www.basketball-reference.com/play-index/psl_finder.cgi?request=1&match=single&type=advanced&per_minute_base=36&per_poss_base=100&lg_id=NBA&is_playoffs=N&year_min=1997&year_max=2020&franch_id=&season_start=1&season_end=2&age_min=0&age_max=99&shoot_hand=&height_min=0&height_max=99&birth_country_is=Y&birth_country=&birth_state=&college_id=&draft_year=&is_active=&debut_yr_nba_start=&debut_yr_nba_end=&is_hof=&is_as=&as_comp=gt&as_val=0&award=&pos_is_g=Y&pos_is_gf=Y&pos_is_f=Y&pos_is_fg=Y&pos_is_fc=Y&pos_is_c=Y&pos_is_cf=Y&qual=&c1stat=&c1comp=&c1val=&c2stat=&c2comp=&c2val=&c3stat=&c3comp=&c3val=&c4stat=&c4comp=&c4val=&c5stat=&c5comp=&c6mult=&c6stat=&order_by=player&order_by_asc=&offset={}".format(str(offset*100))
    
    # this is the HTML from the given URL
    html = urlopen(url)
    soup = BeautifulSoup(html)
    # use findALL() to get the column headers
    soup.findAll('tr', limit=2)
    # use getText()to extract the text we need into a list
    headers = [th.getText() for th in soup.findAll('tr', limit=2)[1].findAll('th')]
    # exclude the first column as we will not need the ranking order from Basketball Reference for the analysis
    headers = headers[1:]
    # avoid the first header row
    rows = soup.findAll('tr')[1:]
    
    
    player_stats = [[td.getText() for td in rows[i].findAll('td')]
                for i in range(len(rows))]
    
    stats_adv = pd.concat([stats_adv, pd.DataFrame(player_stats, columns = headers)]).reset_index(drop=True)

In [9]:
stats_adv = stats_adv[1:]

In [10]:
stats_adv.head(10)

,Season,Age,Tm,Lg,Player,G,GS,MP,PER,3PAr,...,ORtg,DRtg,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
1,1996-97,29,POR,NBA,Aleksandar Đorđević,8,0,61,12.5,.438,...,116,111,0.1,0.0,0.1,.114,2.0,-0.8,1.1,0.1
2,2016-17,19,LAL,NBA,Ivica Zubac,38,11,609,17.0,.013,...,108,110,0.6,0.5,1.1,.086,-1.2,-0.6,-1.7,0.0
3,2017-18,20,LAL,NBA,Ivica Zubac,43,0,410,15.3,.008,...,111,107,0.5,0.5,1.0,.118,-1.8,-0.3,-2.0,0.0
4,2017-18,21,CLE,NBA,Ante Žižić,32,2,214,24.2,.000,...,137,111,0.9,0.2,1.0,.231,1.9,-0.9,1.0,0.2
5,2018-19,22,CLE,NBA,Ante Žižić,59,25,1082,16.2,.000,...,116,117,1.7,0.3,2.0,.087,-1.1,-2.1,-3.2,-0.3
6,2016-17,22,CHI,NBA,Paul Zipser,44,18,843,6.9,.448,...,96,109,-0.3,0.8,0.5,.030,-4.2,-0.2,-4.4,-0.5
7,2017-18,23,CHI,NBA,Paul Zipser,54,12,824,5.2,.470,...,84,112,-1.1,0.6,-0.6,-.034,-5.5,-0.5,-6.1,-0.8
8,2016-17,20,ORL,NBA,Stephen Zimmerman,19,0,108,7.3,.000,...,86,108,-0.1,0.1,0.0,-.005,-6.6,-1.7,-8.3,-0.2
9,2005-06,24,NJN,NBA,Derrick Zimmerman,2,0,32,5.5,.000,...,88,108,0.0,0.0,0.0,.004,-7.7,-2.7,-10.4,-0.1
10,1996-97,23,TOT,NBA,George Zídek,52,2,376,10.2,.017,...,100,111,0.1,0.2,0.3,.034,-4.4,-2.6,-6.9,-0.5

In [11]:
stats_adv.shape

(3359, 29)

In [12]:
stats.loc[stats['Player'] == 'Kobe Bryant']

,Season,Age,Tm,Lg,Player,G,GS,MP,FG,FGA,...,BLK,TOV,PF,PTS,FG%,2P%,3P%,eFG%,FT%,TS%
2972,1996-97,18,LAL,NBA,Kobe Bryant,71,6,15.5,2.5,5.9,...,0.3,1.6,1.4,7.6,.417,.437,.375,.477,.819,.544
2973,1997-98,19,LAL,NBA,Kobe Bryant,79,1,26.0,4.9,11.6,...,0.5,2.0,2.3,15.4,.428,.456,.341,.469,.794,.548

In [25]:
df = stats.copy()
df.columns

Index(['Season', 'Age', 'Tm', 'Lg', 'Player', 'G', 'GS', 'MP', 'FG', 'FGA',
       '2P', '2PA', '3P', '3PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS', 'FG%', '2P%', '3P%', 'eFG%', 'FT%',
       'TS%'],
      dtype='object')

In [26]:
stats_adv.columns

Index(['Season', 'Age', 'Tm', 'Lg', 'Player', 'G', 'GS', 'MP', 'PER', '3PAr',
       'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%',
       'ORtg', 'DRtg', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM',
       'VORP'],
      dtype='object')

In [27]:
# maybe change some of these to reduce redundancy
basic_cols = ['Age', 'Tm', 'G', 'GS', 'MP', 'FGA',
       '2PA', '3PA', 'FTA', 'ORB', 'DRB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS', 'FG%', '2P%', '3P%', 'eFG%', 'FT%',
       'TS%']

In [28]:
adv_cols = [ 'PER', '3PAr',
       'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%',
       'ORtg', 'DRtg', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM',
       'VORP']

In [29]:
advdf = stats_adv.copy()

In [30]:
for col in basic_cols:
    df[col + '_year1'] = 0
    df[col + '_year2'] = 0
    
for col in adv_cols:
    df[col + '_year1'] = 0
    df[col + '_year2'] = 0

In [31]:
df.columns

Index(['Season', 'Age', 'Tm', 'Lg', 'Player', 'G', 'GS', 'MP', 'FG', 'FGA',
       ...
       'WS/48_year1', 'WS/48_year2', 'OBPM_year1', 'OBPM_year2', 'DBPM_year1',
       'DBPM_year2', 'BPM_year1', 'BPM_year2', 'VORP_year1', 'VORP_year2'],
      dtype='object', length=119)

In [32]:
df = df.sort_values(by=['Season'])
advdf = advdf.sort_values(by=['Season'])

In [33]:
df.head()

,Season,Age,Tm,Lg,Player,G,GS,MP,FG,FGA,...,WS/48_year1,WS/48_year2,OBPM_year1,OBPM_year2,DBPM_year1,DBPM_year2,BPM_year1,BPM_year2,VORP_year1,VORP_year2
1,1996-97,29,POR,NBA,Aleksandar Đorđević,8,0,7.6,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0
1468,1996-97,24,CLE,NBA,Donny Marshall,56,0,9.8,0.9,2.9,...,0,0,0,0,0,0,0,0,0,0
254,1996-97,22,POR,NBA,Rasheed Wallace,62,56,30.5,6.1,11.0,...,0,0,0,0,0,0,0,0,0,0
256,1996-97,22,NYK,NBA,John Wallace,68,6,11.6,1.8,3.5,...,0,0,0,0,0,0,0,0,0,0
260,1996-97,22,WSB,NBA,Ben Wallace,34,0,5.8,0.5,1.4,...,0,0,0,0,0,0,0,0,0,0

In [34]:
for player in df['Player'].unique():
    playerstats = df.loc[df['Player'] == player].reset_index(drop = True)
    advplayerstats = advdf.loc[advdf['Player'] == player].reset_index(drop = True)
    if len(playerstats) < 2 or len(advplayerstats) < 2:
        df = df.drop(df[df['Player'] == player].index).reset_index(drop = True)
        advdf = advdf.drop(advdf[advdf['Player'] == player].index).reset_index(drop = True)
        continue
    else:
        for col in basic_cols:
            df[col + "_year1"][df[df['Player'] == player].index] = playerstats[col][0]
            df[col + "_year2"][df[df['Player'] == player].index] = playerstats[col][1]
        for col in adv_cols:
            df[col + "_year1"][df[df['Player'] == player].index] = advplayerstats[col][0]
            df[col + "_year2"][df[df['Player'] == player].index] = advplayerstats[col][1]

/Users/coleleppert/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/coleleppert/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/coleleppert/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/Users/coleleppert/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [35]:
df = df.sort_values(by=['Season']).drop_duplicates(subset ="Player",keep='first').reset_index(drop=True)

In [40]:
df.drop(columns=[*basic_cols, 'Lg', 'FG', '2P', '3P', 'FT', 'TRB'], inplace = True)

In [41]:
df.head(15)

,Season,Player,Age_year1,Age_year2,Tm_year1,Tm_year2,G_year1,G_year2,GS_year1,GS_year2,...,WS/48_year1,WS/48_year2,OBPM_year1,OBPM_year2,DBPM_year1,DBPM_year2,BPM_year1,BPM_year2,VORP_year1,VORP_year2
0,1996-97,John Wallace,22,23,NYK,TOR,68,82,6,36,...,.095,.031,-2.5,-1.1,1.1,-1.9,-1.3,-3.0,0.1,-0.6
1,1996-97,Darvin Ham,23,24,TOT,WAS,36,71,3,3,...,.018,.069,-4.3,-4.6,-0.2,0.5,-4.5,-4.0,-0.2,-0.3
2,1996-97,Steve Nash,22,23,PHO,PHO,65,76,2,9,...,.047,.137,-2.0,1.1,-1.1,0.3,-3.1,1.4,-0.2,1.4
3,1996-97,Mark Hendrickson,22,23,PHI,SAC,29,48,1,1,...,.054,.049,-2.9,-3.5,-2.2,0.1,-5.1,-3.5,-0.2,-0.3
4,1996-97,Jermaine O'Neal,18,19,POR,POR,45,60,0,9,...,.087,.073,-2.5,-3.6,-0.9,0.5,-3.5,-3.0,-0.2,-0.2
5,1996-97,Jeff McInnis,22,24,DEN,WAS,13,35,0,6,...,.060,.019,2.9,-1.3,-2.7,-0.5,0.3,-1.8,0.1,0.0
6,1996-97,Shane Heal,26,33,MIN,SAS,43,6,0,0,...,-.086,-.006,-4.0,-3.2,-2.8,-0.4,-6.8,-3.6,-0.3,0.0
7,1996-97,Erick Dampier,21,22,IND,GSW,72,82,21,82,...,.040,.072,-4.4,-2.2,0.7,-0.2,-3.7,-2.4,-0.4,-0.3
8,1996-97,Reggie Geary,23,24,CLE,SAS,39,62,0,2,...,.056,.023,-3.8,-5.6,2.4,2.7,-1.4,-2.9,0.0,-0.2
9,1996-97,Gary Trent,22,20,POR,POR,82,15,28,1,...,.139,-.092,0.2,-6.6,-0.1,-4.2,0.1,-10.8,1.0,-0.2
10,1996-97,Michael Hawkins,24,26,BOS,SAC,29,24,0,0,...,.033,.011,-2.9,-2.5,-1.0,-1.2,-3.9,-3.7,-0.2,-0.1
11,1996-97,Moochie Norris,23,25,VAN,SEA,8,12,0,0,...,-.066,-.057,-3.9,-3.8,-1.9,-0.4,-5.9,-4.3,-0.1,-0.1
12,1996-97,Marcus Brown,22,25,POR,DET,21,6,0,0,...,.105,-.095,-0.9,-6.7,0.0,-2.6,-1.0,-9.3,0.0,-0.1
13,1996-97,Kobe Bryant,18,19,LAL,LAL,71,79,6,1,...,.079,.147,-0.2,2.2,0.1,-0.8,-0.1,1.4,0.5,1.8
14,1996-97,Jerome Williams,23,24,DET,DET,33,77,0,3,...,.049,.166,-3.1,0.7,0.3,-0.1,-2.8,0.6,0.0,0.9

In [42]:
df.loc[df['Player'] == 'Kobe Bryant']

,Season,Player,Age_year1,Age_year2,Tm_year1,Tm_year2,G_year1,G_year2,GS_year1,GS_year2,...,WS/48_year1,WS/48_year2,OBPM_year1,OBPM_year2,DBPM_year1,DBPM_year2,BPM_year1,BPM_year2,VORP_year1,VORP_year2
13,1996-97,Kobe Bryant,18,19,LAL,LAL,71,79,6,1,...,.079,.147,-0.2,2.2,0.1,-0.8,-0.1,1.4,0.5,1.8

In [43]:
all_stars = pd.DataFrame()

In [44]:

# URL page we will scraping (see image above)
url = "https://www.basketball-reference.com/awards/all_star_by_player.html"
# this is the HTML from the given URL
html = urlopen(url)
soup = BeautifulSoup(html)
# use findALL() to get the column headers
soup.findAll('tr', limit=2)
# use getText()to extract the text we need into a list
headers = [th.getText() for th in soup.findAll('tr', limit=2)[0].findAll('th')]
# exclude the first column as we will not need the ranking order from Basketball Reference for the analysis
#headers = headers[1:]
# avoid the first header row
rows = soup.findAll('tr')[1:]
players = [[td.getText() for td in rows[i].findAll('td')]
            for i in range(len(rows))]
print(headers)
all_stars = pd.concat([all_stars, pd.DataFrame(players, columns = headers)]).reset_index(drop=True)

['Rk', 'Player', 'Tot', 'NBA', 'ABA']

In [45]:
# List of all all stars in NBA history
all_stars.head()

  Rk               Player Tot NBA ABA
0  1  Kareem Abdul-Jabbar  19  19   0
1  2          Kobe Bryant  18  18   0
2  3        Julius Erving  16  11   5
3  4         LeBron James  16  16   0
4  5           Tim Duncan  15  15   0

In [46]:
allStarDict = {}
for player, num in zip(all_stars['Player'], all_stars['Tot']):
    allStarDict[player] = num

In [47]:
df['all_star'] = df['Player'].apply(lambda x: 1 if x in allStarDict else 0)

In [48]:
df[df['all_star'] == 1]

,Season,Player,Age_year1,Age_year2,Tm_year1,Tm_year2,G_year1,G_year2,GS_year1,GS_year2,...,WS/48_year2,OBPM_year1,OBPM_year2,DBPM_year1,DBPM_year2,BPM_year1,BPM_year2,VORP_year1,VORP_year2,all_star
2,1996-97,Steve Nash,22,23,PHO,PHO,65,76,2,9,...,.137,-2.0,1.1,-1.1,0.3,-3.1,1.4,-0.2,1.4,1
4,1996-97,Jermaine O'Neal,18,19,POR,POR,45,60,0,9,...,.073,-2.5,-3.6,-0.9,0.5,-3.5,-3.0,-0.2,-0.2,1
13,1996-97,Kobe Bryant,18,19,LAL,LAL,71,79,6,1,...,.147,-0.2,2.2,0.1,-0.8,-0.1,1.4,0.5,1.8,1
29,1996-97,Ben Wallace,22,23,WSB,WAS,34,67,0,16,...,.125,-7.6,-1.6,-0.7,2.3,-8.3,0.7,-0.3,0.8,1
30,1996-97,Antoine Walker,20,21,BOS,BOS,82,82,68,82,...,.070,-0.3,1.6,-1.8,-1.0,-2.1,0.6,-0.1,2.2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1209,2017-18,Ben Simmons,21,22,PHI,PHI,81,79,81,79,...,.146,2.0,2.2,2.5,1.3,4.5,3.6,4.5,3.8,1
1240,2017-18,Jayson Tatum,19,20,BOS,BOS,80,79,80,79,...,.097,0.0,-0.4,1.2,0.2,1.2,-0.2,2.0,1.1,1
1255,2017-18,Donovan Mitchell,21,22,UTA,UTA,79,77,71,77,...,.092,0.9,1.2,0.3,0.1,1.2,1.3,2.2,2.2,1
1319,2018-19,Trae Young,20,21,ATL,ATL,81,60,81,60,...,.133,2.3,6.3,-2.8,-2.3,-0.6,4.0,0.9,3.2,1
1343,2018-19,Luka Dončić,19,20,DAL,DAL,72,61,72,61,...,.207,3.6,7.4,0.3,1.1,3.9,8.4,3.4,5.4,1

In [49]:
rising_stars = pd.DataFrame()

In [50]:
for year in range(2000,2021):
    # URL page we will scraping (see image above)
    url = "https://www.basketball-reference.com/allstar/NBA_{}_rookie.html".format(year)
    # this is the HTML from the given URL
    html = urlopen(url)
    soup = BeautifulSoup(html)
    # use findALL() to get the column headers
    soup.findAll('tr', limit=2)
    # use getText()to extract the text we need into a list
    headers = [th.getText() for th in soup.findAll('tr', limit=6)[5].findAll('th')]
    # exclude the first column as we will not need the ranking order from Basketball Reference for the analysis
    headers = headers
    # avoid the first header row
    rows = soup.findAll('tr')
    players = [[td.getText() for td in rows[i].findAll(['td','th'])] for i in range(len(rows))]
    rising_stars = pd.concat([rising_stars, pd.DataFrame(players, columns = headers)]).reset_index(drop=True)

In [51]:
# List of all rising stars in NBA

#CLEAN THIS UP
rising_stars

,Player,Tm,MP,FG,FGA,3P,3PA,FT,FTA,ORB,...,AST,STL,BLK,TOV,PF,PTS,FG%,3P%,FT%,Starters
0,,Scoring,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,NaN
1,,1,2,OT,T,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,NaN
2,Rookies,44,37,11,92,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,NaN
3,Sophomores,41,40,2,83,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,NaN
4,,Totals,Shooting,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656,NaN,WAS,16:15,6,9,1,2,3,4,3,...,0,2,0,0,2,16,.667,.500,.750,Moritz Wagner
657,NaN,DET,16:15,2,11,2,9,0,0,1,...,2,0,0,1,0,6,.182,.222,,Sviatoslav Mykhailiuk
658,NaN,MIN,16:15,2,5,1,4,0,0,2,...,5,0,1,5,1,5,.400,.250,,Josh Okogie
659,NaN,NOP,16:15,1,3,1,2,0,0,1,...,2,0,0,1,0,3,.333,.500,,Nicolò Melli
660,NaN,,200,55,109,12,49,9,12,14,...,32,9,3,12,8,131,.505,.245,.750,Team Totals

In [52]:
risingstarsDict = {}
for player in rising_stars['Starters']:
    risingstarsDict[player] = 1

In [53]:
df['rising_star'] = df['Player'].apply(lambda x: 1 if x in risingstarsDict else 0)

In [54]:
df.head()

,Season,Player,Age_year1,Age_year2,Tm_year1,Tm_year2,G_year1,G_year2,GS_year1,GS_year2,...,OBPM_year1,OBPM_year2,DBPM_year1,DBPM_year2,BPM_year1,BPM_year2,VORP_year1,VORP_year2,all_star,rising_star
0,1996-97,John Wallace,22,23,NYK,TOR,68,82,6,36,...,-2.5,-1.1,1.1,-1.9,-1.3,-3.0,0.1,-0.6,0,0
1,1996-97,Darvin Ham,23,24,TOT,WAS,36,71,3,3,...,-4.3,-4.6,-0.2,0.5,-4.5,-4.0,-0.2,-0.3,0,0
2,1996-97,Steve Nash,22,23,PHO,PHO,65,76,2,9,...,-2.0,1.1,-1.1,0.3,-3.1,1.4,-0.2,1.4,1,0
3,1996-97,Mark Hendrickson,22,23,PHI,SAC,29,48,1,1,...,-2.9,-3.5,-2.2,0.1,-5.1,-3.5,-0.2,-0.3,0,0
4,1996-97,Jermaine O'Neal,18,19,POR,POR,45,60,0,9,...,-2.5,-3.6,-0.9,0.5,-3.5,-3.0,-0.2,-0.2,1,0

In [55]:
df[df['rising_star'] == 1]

,Season,Player,Age_year1,Age_year2,Tm_year1,Tm_year2,G_year1,G_year2,GS_year1,GS_year2,...,OBPM_year1,OBPM_year2,DBPM_year1,DBPM_year2,BPM_year1,BPM_year2,VORP_year1,VORP_year2,all_star,rising_star
390,2003-04,David West,23,24,NOH,NOH,71,30,1,8,...,-0.8,-3.3,0.3,0.1,-0.5,-3.2,0.4,-0.2,1,1
415,2003-04,T.J. Ford,20,22,MIL,MIL,55,72,55,70,...,-1.7,-1.1,-0.6,-0.1,-2.4,-1.2,-0.1,0.5,0,1
438,2004-05,Nenad Krstić,21,22,NJN,NJN,75,80,57,80,...,-2.7,-1.9,-0.5,-0.4,-3.2,-2.2,-0.6,-0.1,0,1
448,2004-05,Andre Iguodala,21,22,PHI,PHI,82,82,82,82,...,-0.7,0.2,2.1,0.4,1.4,0.6,2.3,2.0,1,1
450,2004-05,Ben Gordon,21,22,CHI,CHI,82,80,3,47,...,1.0,0.7,-0.3,-0.3,0.7,0.5,1.4,1.6,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1325,2018-19,Moritz Wagner,21,22,LAL,WAS,43,45,5,5,...,-3.9,-2.0,-0.4,-0.5,-4.3,-2.4,-0.3,-0.1,0,1
1326,2018-19,Deandre Ayton,20,21,PHO,PHO,71,38,70,32,...,1.3,0.7,-1.1,-0.5,0.2,0.2,1.2,0.7,0,1
1335,2018-19,Miles Bridges,20,21,CHO,CHO,80,65,25,64,...,-0.9,-1.5,0.1,-1.0,-0.8,-2.5,0.5,-0.3,0,1
1336,2018-19,Rodions Kurucs,20,21,BRK,BRK,63,47,46,9,...,-2.9,-3.8,0.3,0.9,-2.6,-2.9,-0.2,-0.2,0,1
1343,2018-19,Luka Dončić,19,20,DAL,DAL,72,61,72,61,...,3.6,7.4,0.3,1.1,3.9,8.4,3.4,5.4,1,1

In [56]:
df.to_csv('../Data/nba-stats-first2seasons.csv', index=False)